#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

bash $SCRIPT_DIR/make_vim
cat $SCRIPT_DIR/.vimoptions | while read l; do
    grep -sqxF "$l" ~/.vimrc || echo "$l" >> ~/.vimrc
done
cat $SCRIPT_DIR/programs/alias | while read l; do
    ALI=${l%:*}
    P_NAME=${l#*:}
    COMM="alias $ALI=$SCRIPT_DIR/programs/$P_NAME"
    grep -sqxF "$COMM" ~/.bash_aliases || echo "$COMM" >> ~/.bash_aliases
done

echo ""
echo -e "\e[1;32m---Done---"
echo -e "\e[1;31m.: Restart terminal to see changes :."
echo -e "\e[1;37m"