#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
A_GIT="alias gitu=$SCRIPT_DIR/gitupload"

echo "$A_GIT" >> ~/.bash_aliases
source ~/.bash_aliases
cat ./vimoptions >> ~/.vimrc
echo ":autocmd BufNewFile  *.js	0r $SCRIPT_DIR/templates/file.js" >> ~/.vimrc
echo ":autocmd BufNewFile  *.py	0r $SCRIPT_DIR/templates/file.py" >> ~/.vimrc
echo DONE!
