#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

FILENAME=$SCRIPT_DIR/.vimoptions
echo "syntax on" > $FILENAME
echo "set autoindent" >> $FILENAME
echo "set smartindent" >> $FILENAME
echo "set showcmd" >> $FILENAME

for ext in js py html rb sh sql
do
    TMP_COMM_NEWFILE="autocmd BufNewFile *.$ext 0r $SCRIPT_DIR/templates/file.$ext"
    echo $TMP_COMM_NEWFILE >> $FILENAME
done

echo "set shiftwidth=4" >> $FILENAME
echo "set softtabstop=4" >> $FILENAME
echo "set tabstop=4" >> $FILENAME
echo "autocmd Filetype html setlocal expandtab" >> $FILENAME
echo "autocmd Filetype ruby setlocal expandtab" >> $FILENAME
echo "autocmd Filetype javascript setlocal ts=2 sw=2 sts=2 expandtab" >> $FILENAME
echo "autocmd Filetype python setlocal expandtab" >> $FILENAME