#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

FILENAME=$SCRIPT_DIR/.vimoptions
echo "syntax on" > $FILENAME
echo "set autoindent" >> $FILENAME
echo "set smartindent" >> $FILENAME
echo "set showcmd" >> $FILENAME

for ext in js py html rb sh sql pp
do
    TMP_COMM_NEWFILE="autocmd BufNewFile *.$ext 0r $SCRIPT_DIR/templates/file.$ext"
    echo $TMP_COMM_NEWFILE >> $FILENAME
done

echo "set shiftwidth=2" >> $FILENAME
echo "set softtabstop=2" >> $FILENAME
echo "set tabstop=2" >> $FILENAME
echo "set expandtab" >> $FILENAME
echo "autocmd Filetype html setlocal ts=4 sw=4 sts=4" >> $FILENAME
echo "autocmd Filetype ruby setlocal ts=4 sw=4 sts=4" >> $FILENAME
echo "autocmd Filetype python setlocal ts=4 sw=4 sts=4" >> $FILENAME
echo "autocmd Filetype c setlocal ts=4 sw=4 sts=4 noexpandtab" >> $FILENAME
